call code --install-extension bradlc.vscode-tailwindcss
call code --install-extension CoenraadS.bracket-pair-colorizer
call code --install-extension dkundel.vscode-new-file
call code --install-extension ms-azuretools.vscode-docker
call code --install-extension ms-vscode.csharp
call code --install-extension octref.vetur
call code --install-extension redhat.vscode-yaml
call code --install-extension ritwickdey.live-sass
call code --install-extension ritwickdey.LiveServer
call code --install-extension robinbentley.sass-indented
call code --install-extension shd101wyy.markdown-preview-enhanced
call code --install-extension sleistner.vscode-fileutils
call code --install-extension tht13.html-preview-vscode
